outpost_enabled: true
outpost_roi:
  - 2199
  - 1702
  - 78
  - 30
outpost_score_threshold: 0.1
outpost_miss_timeout_s: 1.5
outpost_mappoints_red:
  - 439
  - 92
outpost_mappoints_blue:
  - 280
  - 291
