<?xml version="1.0"?>
<package format="3">
<name>radar27_visualization</name><version>0.1.0</version>
<description>Optional Qt, map and RViz visualization</description>
<maintainer email="delphine@example.com">delphine</maintainer><license>MIT</license>
<buildtool_depend>ament_cmake</buildtool_depend>
<depend>rclcpp</depend>
<depend>rclcpp_components</depend>
<depend>radar27_interfaces</depend>
<depend>rm_field</depend>
<depend>sensor_msgs</depend>
<depend>cv_bridge</depend>
<depend>std_msgs</depend>
<depend>std_srvs</depend>
<depend>geometry_msgs</depend>
<depend>visualization_msgs</depend>
<depend>tf2</depend>
<depend>tf2_ros</depend>
<depend>libopencv-dev</depend>
<depend>yaml-cpp</depend>
<depend>qtbase5-dev</depend>
<exec_depend>rviz2</exec_depend>
<export><build_type>ament_cmake</build_type></export>
</package>
