video_node:
  ros__parameters:
    topic_name: /image_raw
    fps: 20
    synthetic_stamp: false
camera_node:
  ros__parameters:
    camera_brand: hik
    camera_sn: DA7831910
    auto_white_balance: true
    exposure_time: 6000
    gain: 0.7
    gamma: 0.3
    topic_name: /image_raw
    frame_id: camera_frame
    enable_recording: true
    record_fps: 20.0
    record_bitrate_kbps: 15000
    max_record_queue_size: 8
